import { global } from "@/config/global.routes";
import theme from "@/styles/theme";
import {
  AppBar,
  Box,
  Button,
  CssBaseline,
  ThemeProvider,
  Toolbar,
  Typography,
} from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { Fragment, Suspense } from "react";
import Loading from "./loading";

type Route = {
  path: string;
  name: string;
};

type Routes = {
  [key: string]: Route[];
};

const routes: Routes = {
  global,
};

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XML Creator",
  description: "Generated by Peixola",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body className={poppins.className}>
          <AppRouterCacheProvider>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
              <Suspense fallback={<Loading />}>
                <Box sx={{ flexGrow: 1 }}>
                  <AppBar position="static">
                    <Toolbar>
                      <Typography
                        variant="h6"
                        component="div"
                        sx={{ flexGrow: 1 }}
                      >
                        XML creator
                      </Typography>
                      {Object.entries(routes).map(([key, value]) => (
                        <Fragment key={key}>
                          {value.map((route) => (
                            <Link href={route.path} key={route.path}>
                              <Button
                                sx={{ color: "common.white" }}
                                variant="outlined"
                                key={route.path}
                              >
                                {route.name}
                              </Button>
                            </Link>
                          ))}
                        </Fragment>
                      ))}
                    </Toolbar>
                  </AppBar>
                </Box>
                {children}
              </Suspense>
            </main>
          </AppRouterCacheProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
