// import '@/styles/globals.css';
import theme from "@/styles/theme";
import {
  AppBar,
  Box,
  Button,
  CssBaseline,
  ThemeProvider,
  Toolbar,
  Typography,
} from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { Suspense } from "react";
import Loading from "./loading";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XML Creator",
  description: "Generated by Peixola",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body className={poppins.className}>
          <AppRouterCacheProvider>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
              <Suspense fallback={<Loading />}>
                <Box sx={{ flexGrow: 1 }}>
                  <AppBar position="static">
                    <Toolbar>
                      <Typography
                        variant="h6"
                        component="div"
                        sx={{ flexGrow: 1 }}
                      >
                        XML creator
                      </Typography>
                      <Link href="/">
                        <Button
                          sx={{ color: "common.white" }}
                          variant="outlined"
                        >
                          Início
                        </Button>
                      </Link>
                      <Link href="/border">
                        <Button
                          sx={{ color: "common.white" }}
                          variant="outlined"
                        >
                          Borders
                        </Button>
                      </Link>
                      <Link href="/ground">
                        <Button
                          sx={{ color: "common.white" }}
                          variant="outlined"
                        >
                          Grounds
                        </Button>
                      </Link>
                      <Link href="/brush">
                        <Button
                          sx={{ color: "common.white" }}
                          variant="outlined"
                        >
                          Brushes
                        </Button>
                      </Link>
                    </Toolbar>
                  </AppBar>
                </Box>
                {children}
              </Suspense>
            </main>
          </AppRouterCacheProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
